src/Entity/Fiche.php
<?php

namespace App\Entity;

use App\Repository\FicheRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FicheRepository::class)
 */
class Fiche
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_de_naissance;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(?\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }
}

src/Form/FicheType.php
<?php

namespace App\Form;

use App\Entity\Fiche;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FicheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_de_naissance', DateType::class, [
                'widget' => 'single_text',
                'html5' => false,
                'attr' => ['class' => 'js-datepicker'],
                'format' => 'dd-MM-yyyy',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Fiche::class,
        ]);
    }
}

src/Controller/FicheController.php
<?php

namespace App\Controller;

use App\Entity\Fiche;
use App\Form\FicheType;
use App\Repository\FicheRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/fiche")
 */
class FicheController extends AbstractController
{
    /**
     * @Route("/", name="fiche_index", methods={"GET"})
     */
    public function index(FicheRepository $ficheRepository): Response
    {
        return $this->render('fiche/index.html.twig', [
            'fiches' => $ficheRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="fiche_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $fiche = new Fiche();
        $form = $this->createForm(FicheType::class, $fiche);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($fiche);
            $entityManager->flush();

            return $this->redirectToRoute('fiche_index');
        }

        return $this->render('fiche/new.html.twig', [
            'fiche' => $fiche,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fiche_show", methods={"GET"})
     */
    public function show(Fiche $fiche): Response
    {
        return $this->render('fiche/show.html.twig', [
            'fiche' => $fiche,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="fiche_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Fiche $fiche): Response
    {
        $form = $this->createForm(FicheType::class, $fiche);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('fiche_index');
        }

        return $this->render('fiche/edit.html.twig', [
            'fiche' => $fiche,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fiche_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Fiche $fiche): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fiche->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($fiche);
            $entityManager->flush();
        }

        return $this->redirectToRoute('fiche_index');
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\FicheRepository;
use App\Entity\Fiche;

class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(FicheRepository $fiche)
    {
        $fiche = $fiche->findOneBy([
            'id' =>1]);
        dump($fiche);
        

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'fiche' => $fiche
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="css/normalize.css" type="text/css">
        <link rel="stylesheet" href="css/animate.css" type="text/css">
        <link rel="stylesheet" href="css/transition-animations.css" type="text/css">
        <link rel="stylesheet" href="css/owl.carousel.css" type="text/css">
        <link rel="stylesheet" href="css/magnific-popup.css" type="text/css">
        <link rel="stylesheet" href="css/main.css" type="text/css">

    
        <script src="js/jquery-2.1.3.min.js"></script>
        <script src="js/modernizr.custom.js"></script>
        <script src='https://www.google.com/recaptcha/api.js'></script>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
            <script type="text/javascript" src="js/bootstrap.min.js"></script>
            <script type="text/javascript" src="js/pages-switcher.js"></script>
            <script type="text/javascript" src="js/imagesloaded.pkgd.min.js"></script>
            <script type="text/javascript" src="js/validator.js"></script>
            <script type="text/javascript" src="js/jquery.shuffle.min.js"></script>
            <script type="text/javascript" src="js/masonry.pkgd.min.js"></script>
            <script type="text/javascript" src="js/owl.carousel.min.js"></script>
            <script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
            <script type="text/javascript" src="js/jquery.hoverdir.js"></script>
            <!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR-API-KEY"></script>-->
            <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
            <script type="text/javascript" src="js/jquery.googlemap.js"></script>
            <script type="text/javascript" src="js/main.js"></script>
        {% block javascripts %}{% endblock %}
            <script>
                $(document).ready(function() {
                    // you may need to change this code if you are not using Bootstrap Datepicker
                    $('.js-datepicker').datepicker({
                        format: 'yyyy-mm-dd'
                    });
                });
            </script>
    </body>
</html>

templates/base_admin.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="css/bootstrap.min.css" type="text/css">
        <link rel="stylesheet" href="css/normalize.css" type="text/css">
        <link rel="stylesheet" href="css/animate.css" type="text/css">
        <link rel="stylesheet" href="css/transition-animations.css" type="text/css">
        <link rel="stylesheet" href="css/owl.carousel.css" type="text/css">
        <link rel="stylesheet" href="css/magnific-popup.css" type="text/css">
        <link rel="stylesheet" href="css/main.css" type="text/css">
        <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.min.css" type="text/css">

    
        <script src="js/jquery-2.1.3.min.js"></script>
        <script src="js/modernizr.custom.js"></script>
        <script src='https://www.google.com/recaptcha/api.js'></script>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#">Administration</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarColor01">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">Accueil <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{path('home')}}">Retour site</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{path('fiche_index')}}">Mes information</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">About</a>
                </li>
              </ul>
            </div>
          </nav>
        {% block body %}{% endblock %}
            <script type="text/javascript" src="js/bootstrap.min.js"></script>
            <script type="text/javascript" src="js/pages-switcher.js"></script>
            <script type="text/javascript" src="js/imagesloaded.pkgd.min.js"></script>
            <script type="text/javascript" src="js/validator.js"></script>
            <script type="text/javascript" src="js/jquery.shuffle.min.js"></script>
            <script type="text/javascript" src="js/masonry.pkgd.min.js"></script>
            <script type="text/javascript" src="js/owl.carousel.min.js"></script>
            <script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script>
            <script type="text/javascript" src="js/jquery.hoverdir.js"></script>
            <!--<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR-API-KEY"></script>-->
            <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
            <script type="text/javascript" src="js/jquery.googlemap.js"></script>
            <script type="text/javascript" src="js/main.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
        {% block javascripts %}{% endblock %}
            <script>
                $(document).ready(function() {
                    // you may need to change this code if you are not using Bootstrap Datepicker
                    $('.js-datepicker').datepicker({
                        format: 'yyyy-mm-dd'
                    });
                });
            </script>
    </body>
</html>

templates/fiche/_delete_form.html.twig
<form method="post" action="{{ path('fiche_delete', {'id': fiche.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fiche.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fiche/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fiche/edit.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Edit Fiche{% endblock %}

{% block body %}
    <h1>Edit Fiche</h1>

    {{ include('fiche/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('fiche_index') }}">back to list</a>

    {{ include('fiche/_delete_form.html.twig') }}
{% endblock %}

templates/fiche/index.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Fiche index{% endblock %}

{% block body %}
    <h1>Fiche index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_de_naissance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fiche in fiches %}
            <tr>
                <td>{{ fiche.id }}</td>
                <td>{{ fiche.nom }}</td>
                <td>{{ fiche.prenom }}</td>
                <td>{{ fiche.dateDeNaissance ? fiche.dateDeNaissance|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('fiche_show', {'id': fiche.id}) }}">show</a>
                    <a href="{{ path('fiche_edit', {'id': fiche.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('fiche_new') }}">Create new</a>
{% endblock %}

templates/fiche/new.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}New Fiche{% endblock %}

{% block body %}
    <h1>Create new Fiche</h1>

    {{ include('fiche/_form.html.twig') }}

    <a href="{{ path('fiche_index') }}">back to list</a>
{% endblock %}

templates/fiche/show.html.twig
{% extends 'base_admin.html.twig' %}

{% block title %}Fiche{% endblock %}

{% block body %}
    <h1>Fiche</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fiche.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ fiche.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ fiche.prenom }}</td>
            </tr>
            <tr>
                <th>Date_de_naissance</th>
                <td>{{ fiche.dateDeNaissance ? fiche.dateDeNaissance|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('fiche_index') }}">back to list</a>

    <a href="{{ path('fiche_edit', {'id': fiche.id}) }}">edit</a>

    {{ include('fiche/_delete_form.html.twig') }}
{% endblock %}